-- MySQL Script generated by MySQL Workbench
-- Thu Jul 16 16:32:45 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Parks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Parks` (
  `idParks` INT NOT NULL AUTO_INCREMENT,
  `ParkName` VARCHAR(45) NOT NULL,
  `ParkHours` VARCHAR(45) NOT NULL,
  `Avail_Rsv` VARCHAR(45) NULL,
  PRIMARY KEY (`idParks`),
  UNIQUE INDEX `idParks_UNIQUE` (`idParks` ASC) VISIBLE,
  UNIQUE INDEX `ParkName_UNIQUE` (`ParkName` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reservations` (
  `idReservations` INT NOT NULL,
  `ParkID` INT NOT NULL,
  `EntryTime` DATETIME NOT NULL,
  PRIMARY KEY (`idReservations`),
  UNIQUE INDEX `idReservations_UNIQUE` (`idReservations` ASC) VISIBLE,
  INDEX `ParkID_idx` (`ParkID` ASC) VISIBLE,
  CONSTRAINT `ParkID`
    FOREIGN KEY (`ParkID`)
    REFERENCES `mydb`.`Parks` (`idParks`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `idUsers` INT NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(45) NOT NULL,
  `PassWord` VARCHAR(45) NOT NULL,
  `Role` VARCHAR(45) NOT NULL,
  `Reservations` INT NULL,
  `Email` VARCHAR(45) NULL,
  `Phone` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsers`),
  UNIQUE INDEX `idUsers_UNIQUE` (`idUsers` ASC) VISIBLE,
  INDEX `Rsvrs_idx` (`Reservations` ASC) VISIBLE,
  CONSTRAINT `Rsvrs`
    FOREIGN KEY (`Reservations`)
    REFERENCES `mydb`.`Reservations` (`idReservations`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Staff` (
  `idStaff` INT NOT NULL,
  `StaffName` VARCHAR(45) NOT NULL,
  `Role` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `ParkID` INT NOT NULL,
  PRIMARY KEY (`idStaff`),
  INDEX `ParkID_idx` (`ParkID` ASC) VISIBLE,
  CONSTRAINT `ParkID`
    FOREIGN KEY (`ParkID`)
    REFERENCES `mydb`.`Parks` (`idParks`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
